name: Continuous Integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Check out repository
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Set up NodeJS
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set version
        run: echo "VERSION=$(npm run version --silent)" >> ${GITHUB_ENV}

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: v${{ env.VERSION }}
          TITLE: ${{ env.VERSION }}
        run: gh release create "${TAG}" --generate-notes --title "${TITLE}" build/*.zip
